### PR TITLE
(maint) Fix classpath stuff for Java 9

### LINKED ISSUE #79: kitchensink build fails under Java 9
I'm trying to prep us all for Java 9, and took a look at kitchensink because it uses dynapath (there is a Java 9 issue with dynapath < 0.2.4 - I'll send a PR to update that shortly). Even with the newer dynapath, the kitchensink build fails with:

```
ERROR in (with-additional-classpath-entries-test) (Reflector.java:272)
Uncaught exception, not in assertion.
expected: nil
  actual: java.lang.IllegalArgumentException: No matching field found: getURLs for class jdk.internal.loader.ClassLoaders$AppClassLoader
 at clojure.lang.Reflector.getInstanceField (Reflector.java:272)
    clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:315)
    puppetlabs.kitchensink.classpath_test$fn__353$get_urls__354.invoke (classpath_test.clj:9)
    puppetlabs.kitchensink.classpath_test$fn__353.invokeStatic (classpath_test.clj:17)
    puppetlabs.kitchensink.classpath_test/fn (classpath_test.clj:6)
    clojure.test$test_var$fn__7983.invoke (test.clj:716)
    clojure.test$test_var.invokeStatic (test.clj:716)
    clojure.test$test_var.invoke (test.clj:707)
    clojure.test$test_vars$fn__8005$fn__8010.invoke (test.clj:734)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$test_vars$fn__8005.invoke (test.clj:734)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    clojure.test$test_vars.invokeStatic (test.clj:730)
    clojure.test$test_all_vars.invokeStatic (test.clj:736)
    clojure.test$test_ns.invokeStatic (test.clj:757)
    clojure.test$test_ns.invoke (test.clj:742)
    user$eval85$fn__136.invoke (form-init3789164235670503091.clj:1)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.injected$compose_hooks$fn__19.doInvoke (form-init3789164235670503091.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.injected$run_hooks.invokeStatic (form-init3789164235670503091.clj:1)
    leiningen.core.injected$run_hooks.invoke (form-init3789164235670503091.clj:1)
    leiningen.core.injected$prepare_for_hooks$fn__24$fn__25.doInvoke (form-init3789164235670503091.clj:1)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$map$fn__4785.invoke (core.clj:2646)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.boundedLength (RT.java:1749)
    clojure.lang.RestFn.applyTo (RestFn.java:130)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.test$run_tests.invokeStatic (test.clj:767)
    clojure.test$run_tests.doInvoke (test.clj:767)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    user$eval85$fn__148$fn__179.invoke (form-init3789164235670503091.clj:1)
    user$eval85$fn__148$fn__149.invoke (form-init3789164235670503091.clj:1)
    user$eval85$fn__148.invoke (form-init3789164235670503091.clj:1)
    user$eval85.invokeStatic (form-init3789164235670503091.clj:1)
    user$eval85.invoke (form-init3789164235670503091.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
    clojure.lang.Compiler.eval (Compiler.java:6917)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.main$load_script.invokeStatic (main.clj:275)
    clojure.main$init_opt.invokeStatic (main.clj:277)
    clojure.main$init_opt.invoke (main.clj:277)
    clojure.main$initialize.invokeStatic (main.clj:308)
    clojure.main$null_opt.invokeStatic (main.clj:342)
    clojure.main$null_opt.invoke (main.clj:339)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

This is because the `AppClassLoader` is no longer a `URLClassLoader` under Java 9 - see https://github.com/tobias/clojure-java-9/issues/3

Just wanted to make you aware so you have time to fix it before the Java 9 release (currently [July of next year](http://www.java9countdown.xyz)).

### PR DESCRIPTION
**Pull request by pcarlisle**
We can't rely on having a modifiable classloader at all times, so make
sure one is put in place if needed.

Fixes #79

### CODE REVIEW

File: src/puppetlabs/kitchensink/classpath.clj [hunk 1]
```diff
@@ -35,6 +35,15 @@
   [cl]
   (dp/addable-classpath? cl))
 
+(defn- ensure-modifiable-classloader
+  "Check if there is a modifiable classloader in the current hierarchy, and add
+  one if not."
+  []
+  (let [classloader (.. Thread currentThread getContextClassLoader)]
+    (when-not (last (filter modifiable-classloader? (classloader-hierarchy classloader)))
+      (let [new-cl (clojure.lang.DynamicClassLoader. classloader)]
```
Comment (pcarlisle) [inline src/puppetlabs/kitchensink/classpath.clj]: Is it okay to just use the clojure one for this? We could implement our own pretty easily but it seemed to have what was needed.

**Comment by lindboe** [comment]
Commit description might be more useful if it said why we can't rely on having a modifiable classloader (even if it just says "because Java 9 no longer guarantees that" or something)

File: test/puppetlabs/kitchensink/classpath_test.clj [hunk 2]
```diff
@@ -1,12 +1,18 @@
...
   (:import (java.net URL)))
 
 (deftest with-additional-classpath-entries-test
   (let [paths ["/foo" "/bar"]
         get-urls #(into #{}
-                        (.getURLs (.getContextClassLoader (Thread/currentThread))))]
+                        (classpath-urls (.getContextClassLoader (Thread/currentThread))))]
+    ;; Called for side effect of ensuring there's a modifiable classloader
+    ;; without needing to make that function public
+    (add-classpath "file:/nil")
```
Comment (MikaelSmith) [inline test/puppetlabs/kitchensink/classpath_test.clj]: This part seems weird. How does `add-classpath` get called otherwise in real use?

Comment (pcarlisle) [reply test/puppetlabs/kitchensink/classpath_test.clj]: It gets called on its own in trapperkeeper. It does not normally need to be called before calling the next line, but this test wants to use some url methods after with-additional-classpath-entries removes the temporary classloader it puts there, so this makes that possible. It's not entirely clean.

File: src/puppetlabs/kitchensink/classpath.clj (hunk 1 above)
Comment (haus) [reply src/puppetlabs/kitchensink/classpath.clj]: this seems fine?

File: test/puppetlabs/kitchensink/classpath_test.clj (hunk 2 above)
Comment (pcarlisle) [reply test/puppetlabs/kitchensink/classpath_test.clj]: the way this test works doesn't make that much sense to begin with

File: src/puppetlabs/kitchensink/classpath.clj (hunk 1 above)
Comment (haus) [reply src/puppetlabs/kitchensink/classpath.clj]: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/DynamicClassLoader.java#L33-L38 isn't super readable, but it seems fine and hasn't been touched in years.

File: test/puppetlabs/kitchensink/classpath_test.clj (hunk 2 above)
Comment (pcarlisle) [reply test/puppetlabs/kitchensink/classpath_test.clj]: cleaned this up so it's not confusing anymore

**Comment by MikaelSmith** [comment]
Can we add Java 9 to the test matrix?
